### ISSUE TITLE
mplayer to webcam

### ISSUE THREAD

**Issue by alphonse-lin** [hanyazou/TelloPy#22]
Hey, i have clone ur code and test it, it is so good, it works quite well in my windows 10, but i got a small issue which i cannot really fix it, here it is.

my background is architecture, so i am trying to import the live video from tello into architectural software-rhino or grasshopper by webcam, but i don't really know how to connect mplayer video data into webcam. can we have a discussion when u r free.

thank u so much for sharing ur tellopy platform, it did help alot. I would definitely mention ur contribution in my paper if u dont mind.

**Comment by hanyazou** [comment]
I didn't know rhino and grasshopper at all. I googled to find this page https://rhino.github.io. But I couldn't find any components to use webcam. How can you use webcam with grasshopper? Do you use firefly?

**Comment by alphonse-lin** [comment]
yes...sth.like firefly, it is called falcon, they can both extract data from webcam, and detect them. 

thank u so much for replying me.

**Comment by alphonse-lin** [comment]
i have tried to use udp to send those data into grasshopper(gh), but gh is nor possible to import image(pil), and  bytesIO(os). thus, i gave up sending data through udp, webcam might be a possile way to do it. so i try to build a local http sever, find a software which can create virtual webcam, try to receive the video data from that http sever(sorry, i am just new to cs, my backrgound is architecture)

thank u so much for sharing ur tellpy, i truly mean it..thanks

**Comment by hanyazou** [comment]
It requires some grasshopper and it's plugin knowledge which I don't have. UDP sounds good for me. Is there any components which can convert UDP input into "Raw Video Bitmap" output?

**Comment by alphonse-lin** [comment]
not really, base my knowledge they dont have any thing like that...i asked
some of my friend, they prefer use pycharm to detect apriltags(like qr
code)in video, then transfer the value of that code into gh(like position
value of april tags), which is much better, however, it is almost at the
end of my thesis, i dont really have time to transfer the whole calculation
from gh to python. thats the reason why i raised this issue. i have tried
to import udp to gh, it just really slow, also, cannot convert udp value
into video.


thx
alphonse

hanyazou <notifications@github.com> 于 2018年10月9日周二 上午12:34写道：

**Comment by alphonse-lin** [comment]
![image](https://user-images.githubusercontent.com/38575020/46612749-2c464580-cb5d-11e8-838d-4551fd6e3456.png)
that's how it look in grasshopper(i use ghowl to receive UDP input)

**Comment by alphonse-lin** [comment]
but firefly creates a component which can import video stream into grasshopper... 
![image](https://user-images.githubusercontent.com/38575020/46613314-a9be8580-cb5e-11e8-837b-38d151121241.png)

**Comment by hanyazou** [comment]
I think you can do it like firefly and Kinect if you create your own component.

https://discourse.mcneel.com/t/tutorial-creating-a-grasshopper-component-with-the-python-ghpy-compiler/38552

**Comment by alphonse-lin** [comment]
thank u so much, i would try it out, probably use C# rather than python in grasshopper, i would let u know if i can do achieve the expected result.

**Comment by francisduan** [comment]
Hi there,

Similar question, how to send the udp packet/video to Unity. I am new to udp so I haven't come up with a good solution. I am thinking about using the Webcam from Unity to do this. Could you provide some insights about this?

Thanks

**Comment by hanyazou** [comment]
Hey guys,

You should go your tool/app forum to ask how can you inject UDP video packets into your tool/app before you post question here.
I think 'webcam' is not an answer. You should tell us what is the 'webcam' and how it works with Unity in detail. You could get some help if you show 'webcam' source code for example.
