### ISSUE TITLE
need help with real time image

### ISSUE THREAD

**Issue by dunchen** [hanyazou/TelloPy#3]
Hi! Thank you so much for your code! However I don't know how to get the real time image from the drone. In your example "video effect", the image is delayed for several seconds. Could you tell me how to get the real time image? Thank you very much!

**Comment by vtushevskiy** [comment]
you can do 3 things: skip portion of frames, resize image and do only part of frames

**Comment by hanyazou** [comment]
@dunchen let me please continue our discussion in #5
