### ISSUE TITLE
framework version 01.04.35.01

### ISSUE THREAD

**Issue by mariofraga** [hanyazou/TelloPy#30]
What version of the framework are you using?

I use the version 01.04.35.01 and the video does not work by the computer, only by the mobile app

**Comment by hanyazou** [comment]
According to their release note at https://www.ryzerobotics.com/tello/downloads, there are three version of the firmware.

2018.03.20    v01.03.18.01
2018.05.03    v01.03.33.01
2018.08.16    v01.04.35.01

My app says the firmware version is 01.03.33.01.
