### ISSUE TITLE
Tello: 15:10:13.194: Error: video recv: timeout

### ISSUE THREAD

**Issue by Ballan9** [hanyazou/TelloPy#35]
Hi, I have been running this program lately and am now receiving problems when running it. It no longer connects to the drone properly

**Comment by Ballan9** [comment]
![image](https://user-images.githubusercontent.com/18186113/49131484-1c104280-f324-11e8-9a77-b61d361d30d3.png)

**Comment by hanyazou** [comment]
duplicate with https://github.com/hanyazou/TelloPy/issues/29
