### ISSUE TITLE
Alternative to Tello

### ISSUE THREAD

**Issue by jongse-park** [hanyazou/TelloPy#37]
Hi, maybe this question is not a good fit for this repo but wondered what the TelloPy contributors think about it. I have been looking for programmable drones through SDK, just like Tello. What I mean is that I don't want the mobile or onboard SDK, I want the server-client style SDK that I can communicate with drones through wifi network. Does any of you happen to know other off-the-shelf drones that have a good SDK support and possibly support drone swarming natively? My first programmable drone was Tello and thus it's hard for me to believe that Tello is the best option out there considering its cheap price..

**Comment by GalBrandwine** [comment]
Hey!

Have you heard of Crazyflie? 
And the Crazyswarm project?

The Crazyflie's a bit simpler than the tello, but they are shelf ready swarming drones (more or less)..

Note: 
youll need a treacking system (e.g optitrack), althow the Crazyflie's are super moduler and they Have a lot of sensoring options, im sure you could implement a swarm without a tracking system.

Hope it helps,
Gal.
