### ISSUE TITLE
Sensor data

### ISSUE THREAD

**Issue by freaad** [hanyazou/TelloPy#4]
Hello. Thank you for sharing the good sdk.
Does tello send the imu data such as vellocity, yaw etc?
Thank you.

**Comment by hanyazou** [comment]
Tello._internal.protocol.FlightData seems to have members for velocity though I din't investigate in details.

        self.height = int16(data[0], data[1])
        self.north_speed = int16(data[2], data[3])
        self.east_speed = int16(data[4], data[5])
        self.ground_speed = int16(data[6], data[7])

**Comment by freaad** [comment]
Thank you so much. I will definitely check it.

**Comment by edmondja** [comment]
No accelerometer ?

**Comment by hanyazou** [comment]
@edmondja 
no...
