### ISSUE TITLE
joystick laggy / does not respond

### ISSUE THREAD

**Issue by kekkokk** [hanyazou/TelloPy#41]
hi guys,
I have a strange problem.
ubuntu 18.04 + ps4 controller
I have the video feed and the controller is only able to takeoff and go up and down and rotate clockwise.
the other commands doesn't works.
what could be the problem?

**Comment by hanyazou** [comment]
Please check your joystick with some joystick tester at first.
GUI app jstest-gtk might help you.

The example joystick_and_video.py print your joystick device name like 'Joystick name: ....'.
Check the name of your device and command assignment in the joystick_and_video.py.

**Comment by kekkokk** [comment]
> Please check your joystick with some joystick tester at first.
> GUI app jstest-gtk might help you.
> 
> The example joystick_and_video.py print your joystick device name like 'Joystick name: ....'.
> Check the name of your device and command assignment in the joystick_and_video.py.

Thank you, I'll check asap

**Comment by hanyazou** [comment]
Please re-open if you have any update.
