### ISSUE TITLE
Stop debug information

### ISSUE THREAD

**Issue by rsewell97** [hanyazou/TelloPy#42]
Hi, 

I find the printed debugging information is not always helpful. Is there an easy way to disable this without going into the source code? I'm referring to constant messages such as 
`Tello: 22:58:29.034:  Info: video data 754039 bytes 368.0KB/sec`
`Tello: 22:58:29.074:  Info: counter_clockwise(val=50)`
for example. Btw, nice module - works a treat after fighting with av

**Comment by hanyazou** [comment]
You can suppress those 'Info: ' output by set_loglevel().

```
drone = tellopy.Tello()
drone.set_loglevel(drone.LOG_WARN)
```

**Comment by rsewell97** [comment]
Yep - just found it :) thanks for your help
