### ISSUE TITLE
get current altitude?

### ISSUE THREAD

**Issue by rsewell97** [hanyazou/TelloPy#43]
Just wondering if there's a method to get current altitude from the device from the IR sensors mounted on the underside? I saw #11 regarding orientation - is there a way/are there plans to add an absolute position tracking relative to its liftoff point?

Thanks,

**Comment by hanyazou** [comment]
Did you look at `pos_z` in #11?

**Comment by hanyazou** [comment]
Please re-open this issue when you got any updates.

**Comment by rsewell97** [comment]
Thanks for pointing me in the right direction - now resolved. Regards

**Comment by viet2411** [comment]
@rsewell97 
I can get the value of mvo.pos_z, but I don't understand exactly what it means. Can you tell me how you calculated altidude from these values?
Thank you and best regards.
