### ISSUE TITLE
Where is the images / videos stored?

### ISSUE THREAD

**Issue by iKevv** [hanyazou/TelloPy#51]
I managed to fly the tello drone using keyboard_video code and i was wondering where are the images stored? Also i have mplayer but i have no idea where is the videos are stored..

Any help is appreciated!

**Comment by hanyazou** [comment]
You can find the information in the source code keyboard_and_video.py
That says "~/Pictures".

For example,
~/Pictures/tello-2019-07-06_074800.mp4
~/Pictures/tello-2019-07-06_074800.jpeg

**Comment by iKevv** [comment]
i'm a bit lost here, can you be more specific?
EDIT: I can't find any files name " ~/Pictures.. "
