### ISSUE TITLE
Regular image sampling and latency

### ISSUE THREAD

**Issue by edmondja** [hanyazou/TelloPy#8]
Is there a way to slow down the for loop in the video streaming example : 
"for frame in container.decode(video=0):" so we can use heavy slow computations in each iteration of the loop and keep having a regularly sampled images stream ?

Or maybe we could use http://www.scikit-video.org/stable/ for this instead ?

**Comment by hanyazou** [comment]
How about adding a thread? This works for me.

https://github.com/hanyazou/TelloPy/blob/8f0ae04552972143baadcafd73238a953ba6c48b/tellopy/examples/video_effect.py

**Comment by edmondja** [comment]
Wow thanks, I’ll try to see if this works :)

**Comment by hanyazou** [comment]
Sorry. Line 57 `image = None` in that source is wrong. It should be `frame = None`.

**Comment by edmondja** [comment]
Hey, I took a look at you solution, I think yours is more elegant than what I did before but I don't really see a difference.

Just to understand, why do you use threading instead of just skipping the images which didn't appear until the timer is passed ? like this : 

starting = time.time()
for frame in container.decode(video=0):
    timer = time.time()

    if (timer - starting) * 1000 > 100 :
        starting = timer
        # Here do some heavy computations (heavy but still <100ms)

**Comment by vtushevskiy** [comment]
Thanks for threading example!!

**Comment by vtushevskiy** [comment]
I just checked threading example. 
I did not test it jet, but will there be no conflict of concurrent access to 'frame' variable? 
Shouldn't you lock it when write/read?

**Comment by vtushevskiy** [comment]
Also, I believe there is no necessarity to skip first 300 frames when we use threading. OpenCV part will just access to last available frame.

**Comment by vtushevskiy** [comment]
Just tested it: works perfect. I don't know why but there are no concurrent access conflicts. Also, skipping of first 300 frames is not necessary anymore, there is no lag.
Great improvement!

**Comment by hanyazou** [comment]
I've modified the video_effect.py example on develop-0.5.0 branch.

https://github.com/hanyazou/TelloPy/commit/4f0609e74ddc0beeac9100cb2c04c514754b6f3b

The idea is that it skips subsequent frames if it consume processing time longer than the frame interval. This idea is based on the post by @edmondja.

Thank you, @edmondja !

**Comment by edmondja** [comment]
By the way, does the fact of using the thread  https://github.com/hanyazou/TelloPy/issues/8#issuecomment-399617341 consumes too much CPU the same way the while loop here https://github.com/hanyazou/TelloPy/issues/6#issuecomment-401519284 when you get rid of the sleep ?

**Comment by hanyazou** [comment]
@edmondja 
I think every thread should have some sleep or yield in it's loop. I guess that video decoder have some sleep in it. It is waiting for some input from the source.
