### ISSUE TITLE
Can not record video and capture picture

### ISSUE THREAD

**Issue by viet2411** [hanyazou/TelloPy#82]
Hello everyone,
I was able to control the drone normally using keyboard_and_video.py, but when I toggled record key, the program can't record the video. It returned "Cannot seek backward in linear streams! Seek failed"
Also, when I captured a picture from camera, the screen freezed and I coudn't do anything.
Has anyone solved this problem before? Please tell me how to fix it.

Thank you and best regards.

**Comment by Walt-H** [comment]
See my comment here: [changing the directory for pictures and video
](https://github.com/hanyazou/TelloPy/issues/78#issuecomment-660214525)
